### ISSUE TITLE
Can not run flotilla client and server

### ISSUE THREAD

**Issue by huikang** [tylertreat/Flotilla#7]
# github.com/tylertreat/Flotilla/flotilla-server/daemon
flotilla-server/daemon/daemon.go:132: cannot use rep (type "github.com/go-mangos/mangos".Socket) as type "github.com/gdamore/mangos".Socket in field value:
	"github.com/go-mangos/mangos".Socket does not implement "github.com/gdamore/mangos".Socket (wrong type for AddTransport method)
		have AddTransport("github.com/go-mangos/mangos".Transport)
		want AddTransport("github.com/gdamore/mangos".Transport)

**Comment by tylertreat** [comment]
Fixed in https://github.com/tylertreat/Flotilla/pull/8.
